### ISSUE TITLE
rails generate polymer:component Error

### ISSUE THREAD

**Issue by mibamur** [nevir/polymer-rails#1]
``` bash
$ rails generate polymer:component WebappScaffold
   identical  app/components/webapp_scaffold/webapp_scaffold.html
   identical  app/components/webapp_scaffold/webapp_scaffold.css.scss
      append  app/assets/manifests/application.html
/home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /var/www/russia-taobao.ru/POLYMER_RAILS/polymer1/app/assets/manifests/application.html (Errno::ENOENT)
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/bundler/gems/polymer-rails-2da7bf6d1585/lib/rails/generators/polymer/component/component_generator.rb:44:in `import_globally'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/generators.rb:157:in `invoke'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:51:in `generate'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /home/debadmin/.rvm/gems/ruby-2.1.2@rails414/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'

```

**Comment by nevir** [comment]
Unfortunately, I'm putting this project on hold until I can work out some
issues with HTML imports in sprockets (there's a big sprockets refactor
coming)
